import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/nav";
import Footer from "./_components/footer";
import favicon from "./favicon.ico";
import Provider from "@/app/utils/provider";
import { Toaster } from "@/components/ui/toaster";
import { siteConfig } from "../../config/site";
// import Scroll from "./_components/scroll";

const newIcon = favicon.src;

const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: {
    default: siteConfig.name,
    template: ` ${siteConfig.name} | %s`,
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href={newIcon} />
      </head>
      {/* <Scroll /> */}
      <body className={poppins.className}>
        <Provider>
          <div className="sticky top-0 z-[1] bg-white">
            <Navbar />
          </div>
          {children}
          <Toaster />
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
