import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/nav";
import Footer from "./_components/footer";
import favicon from "./favicon.ico";
import Scroll from "./_components/Scroll";

const newIcon = favicon.src;

const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Resona - Greatest audio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href={newIcon} />
      </head>
      <Scroll />
      <body className={poppins.className}>
        <div className="sticky top-0 z-[100] bg-white">
          <Navbar />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
